##### CONFIGURATION FLAGS #####

# Name of your site (displayed in the header)
name: Albert Saiapin
# Short bio or description (displayed in the header)
description: AI researcher interested in Tensor Networks, Deep Learning, Machine Learning and Uncertainty Estimation
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: #/images/Me.jpg

##### OPTIONAL FLAGS #####
# Includes an icon in the footer for each username you enter
footer-links:
  email: analystalb@gmail.com
  github: albmlpy/
  linkedin: albert-sayapin
  #dribbble: #facebook: #flickr: #instagram: #pinterest: 
  #rss: #twitter: #stackoverflow: #youtube: #googleplus:

# Your website URL (e.g. http://barryclark.github.io); Used for Sitemap.xml and your RSS feed
url: http://albmlpy.github.io 

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
#disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
#google_analytics:

##### OPTIONAL FLAGS #####

#####! DO NOT CHANGE !#####
permalink: /:title/
version: v1.2.0 # The release of Jekyll Now that you're using
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed
# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
#####! DO NOT CHANGE !#####
